deployments:
  - name: Docker
    description: null
    entrypoint: examples/docker/flow.py:call_api
    flow_name: null
    parameters: {}
    schedule: null
    tags: []
    version: null
    work_pool:
      job_variables:
        image: '{{ image_name }}'
      name: docker-pool
      work_queue_name: null
