name: docker
prefect-version: 3.0.0

build:
  - prefect_docker.deployments.steps.build_docker_image:
      requires: prefect-docker>0.6.0
      image_name: EXAMPLE_IMAGE_REGISTRY
      tag: latest
      dockerfile: auto

push: null

pull:
  - prefect.deployments.steps.git_clone:
      repository: git@github.com:PrefectHQ/actions-prefect-deploy.git
      branch: main
      access_token: "{{ prefect.blocks.secret.docker-github-pat }}"

deployments:
  - name: Docker
    description: An example Prefect deployment
    entrypoint: ./flow.py:call_api
    parameters: {}
    schedule: {}
    work_pool:
      job_variables:
        image: prefecthq/prefect:3-latest
      name: docker-pool
