---
name: Deploy a Prefect flow
author: PrefectHQ
description: Deploy a flow from a project by creating a Prefect deployment.
branding:
  icon: upload-cloud
  color: blue

inputs:
  deployment-names:
    description:
      Comma sepearated list of names of your 
      Prefect deployments.
      example 'deployment1,deployment2'
    required: false
    default: deployment

  requirements-file-paths:
    description:
      Comma sepearated list of paths to 
      requirements files to correctly install
      dependencies for your Prefect flow(s).
      example './flow1/requirements.txt,./flow2/requirements.txt'
    required: false
    default: ''

runs:
  using: composite
  steps:
    # Maybe install prefect
    - id: create_lists
      run: |
        IFS=',' read -r -a requirements_paths <<< ${{ inputs.requirements-file-paths }}
        IFS=',' read -r -a deployment_names <<< ${{ inputs.deployment-names }}
        echo "REQUIREMENTS_TXT=${requirements_paths[@]}" >> $GITHUB_ENV
        echo "DEPLOYMENT_NAMES=${deployment_names[@]}" >> $GITHUB_ENV
      shell: bash

    - id: install-local-requirements
      if: ${{ env.REQUIREMENTS_TXT != '' }}
      run: |
        for req in ${REQUIREMENTS_TXT}; do
          pip install -r $req
        done
      shell: bash

    - id: prefect-deploy
      run: |
        for name in ${DEPLOYMENT_NAMES}; do
          prefect deploy --name $name
        done
      shell: bash
