---
name: prefect-deploy-project
author: PrefectHQ
description: Build and Release a Prefect Deployment

inputs:
  prefect-api-key:
    description:
      A Prefect Cloud API key associated with the
      account where the deployment will run from.
    required: true

  prefect-workspace:
    description:
      A Prefect workspace where the deployment will run from.
    required: true

  name:
    description:
      The name to give the deployment.
    required: true

  requirements-file-path:
    description:
      Path to requirements files to correctly install
      dependencies for your Prefect flow(s).
      Defaults to the GH Workspace/requirements.txt.
    required: true
    default: ./requirements.txt

  work-pool:
    description:
      The work pool that will handle this deployment's runs.
    required: true

  entrypoint:
    description:
      The path to a flow entrypoint within a project,
      in the form of `./path/to/file.py:flow_func_name`
      Required unless the `--flow` argument is specified
      in place of the entrypoint.
    required: false

  additional-args:
    description:
      Any additinal arguments that need to be passed to
      the prefect deployment run in a space separated format.
      i.e - `--variable foo=bar -t 1.0.0 --cron "* * * * *"`
    required: false

runs:
  using: composite
  steps:
    - run: pip install -q prefect
      shell: bash
      id: install-prefect-locally
    - run: pip install -r ${{ inputs.requirements-file-path }}
      id: install-local-requirements
      shell: bash
    - run: |
        prefect cloud login \
        --key ${{ inputs.prefect-api-key }} \
        --workspace ${{ inputs.prefect-workspace }}
      id: prefect-cloud-login
      shell: bash
    - run: |
        prefect deploy ${{ inputs.entrypoint }} \
         -n ${{ inputs.name }} \
         -p ${{ inputs.work-pool }} \
         ${{ inputs.additional-args }}
      id: prefect-deploy
      shell: bash
