name: prefect-project-deploy
author: jimid27
description: Build and Release a Prefect Deployment

inputs:
  api-key:
    description: A Prefect Cloud API key.
    required: true
  requirements-file-path:
    description:
      Path to requirements files to correctly install dependencies for your Prefect
      flow(s).  Defaults to the GH Workspace/requirements.txt
    required: true
    default: ${{ GITHUB_WORKSPACE }}/requirements.txt
  entrypoint:
    description: 
      The path to a flow entrypoint within a project, in the form of `./path/to/file.py:flow_func_name`
    required: false
  flow:
    description: 
      The name of a registered flow to create a deployment for. (Use typically in place of Entrypoint)
    required: false
  name:
    description:
      The name to give the deployment. (Defaults to none)
    required: false
  description:
    description: 
      The description to give the deployment. If not provided, the description will be populated from the flow's description.
    required: false
  version:
    description: 
      A version to give the deployment.
    required: false
  tag:
    description:
      One or more optional tags to apply to the deployment. Note - tags are used only for organizational purposes. For delegating work to agents, use the --work-queue flag.
    required: false
  pool:
    description: 
      The work pool that will handle this deployment's runs.
    required: false
  work-queue:
    description:
      The work queue that will handle this deployment's runs. It will be created if it doesn't already exist. Defaults to `None`.
    required: false
  variable: 
    description: 
      One or more job variable overrides for the work pool provided in the format of key=value
    required: false
  cron:
    description:
      A cron string that will be used to set a CronSchedule on the deployment.
    required: false
  interval:
    description:
      An integer specifying an interval (in seconds) that will be used to set an IntervalSchedule on the deployment.
    required: false
  anchor-date:
    description: 
      The anchor date for an interval schedule
    required: false
  rrule:
    description: 
      An RRule that will be used to set an RRuleSchedule on the deployment.
    required: false
  timezone:
    description:
      Deployment schedule timezone string e.g. 'America/New_York'
    required: false
  param:
    description: 
      An optional parameter override, values are parsed as JSON strings e.g. --param question=ultimate --param answer=42
    required: false
  params:
    description: 
      'An optional parameter override in a JSON string format e.g. --params={"question": "ultimate", "answer": 42}'
    required: false

runs:
  using: composite
  steps:
    - run: pip install -r ${{ inputs.requirements-files }}
      shell: bash
    - run: prefect cloud login --key ${{ inputs.api-key }} --workspace ${{ inputs.prefect-workspace }}
      shell: bash
    - run: |
        prefect deploy \
         -f ${{ inputs.flow }} \
         -n ${{ inputs.name }} \
         -d ${{ inputs.description }} \
         --version ${{ inputs.version }} \
         -t ${{ inputs.tag }} \
         -p ${{ inputs.pool }} \
         -q ${{ inputs.work-queue }} \
         -v ${{ inputs.variable }} \
         --cron ${{ inputs.cron }} \
         --interval ${{ inputs.interval }} \
         --anchor-date ${{ inputs.anchor-date }} \
         --rrule ${{ inputs.rrule }} \
         --timezone ${{ inputs.timezone }} \
         --param ${{ inputs.param }} \
         --params ${{ inputs.params }} \
         ${{ inputs.entrypoint}}
      shell: bash
