name: Deploy a Prefect flow to staging/test
on: [push]
jobs:
  deploy_flow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

# TODO: first run tests then deploy
      - name: Prefect Auth
        uses: PrefectHQ/actions-prefect-auth@v1
        with:
          prefect-api-key: ${{ secrets.PREFECT_API_KEY }}  # TODO: use OIDC with organisation or enterprise plan.
          prefect-workspace: ${{ secrets.PREFECT_WORKSPACE }}  # TODO: use staging and production workspaces with organisation or enterprise plan.

      - name: Run Prefect Deploy
        uses: PrefectHQ/actions-prefect-deploy@v3
        with:
          all-deployments: "true"
          requirements-file-paths: ./examples/multi-deployment/deployment-1/requirements.txt,./examples/multi-deployment/deployment-2/requirements.txt
          prefect-file: ./examples/multi-deployment/prefect.yaml

